version: '3.5'

services:
    backend:
      image: example-backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db_postgres
        - POSTGRES_PASSWORD=postgres
    frontend:
      image: example-frontend
      depends_on:
        - redis 
    redis:
      image: redis
      ports:
        -  6379:6379
      depends_on:
        - db
    db:
      image: postgres
      restart: unless-stopped
      container_name: db_postgres
      environment:
        - POSTGRES_PASSWORD=postgres
      depends_on:
        - backend
    web:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      environment:
        - NGINX_HOST=http://localhost
        - NGINX_PORT=80
      depends_on:
        - backend
        - frontend
